name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: DockerHub Login
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build & Push Frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

    - name: AWS Auth
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name lugx-cluster

    - name: Deploy Frontend to EKS
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl set image deployment/lugx-frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -n default
        kubectl rollout status deployment/lugx-frontend -n default
